#########################################################################################
# SIMULATION SETUP                                                                     ##
#                                                                                      ##
# TASK: Creat the seed pattern for each simulations, and creat xml file                ##
# INPUTS: parameter tables                                                             ##
# OUTPUTS: seed files and then XML file                                                ##
# Written by thiery.masserey@swisstph.ch adapted from andrewjames.shattock@swisstph.ch ##
#########################################################################################

# load funcitons requiered
source("myRfunctions.R")
require(pracma)
require(stringr)
require(tgp)
#require(qdap)
require(xlsx)

# -------------------------------------------------------------------
# Generate xml sed replacement patterns for full country simulations.
# -------------------------------------------------------------------
simulation_sed_patterns <- function(pm) {
  
  # Message in the console
  message("  - Generating scenarios")
  
  # File path to parameter table
  param_table_name <- param_set_name(sample_num = pm$sample_num)
  param_file <- paste0(pm$pth$param_table, param_table_name, ".txt")
  
  # Read the parameter table generated by generate_param_table
  if (file.exists(param_file)) {
    param_table <- read.table(param_file, sep = "\t", header = TRUE, as.is = TRUE)
   } else {
    # Throw an error if file cannot be found
    stop("Parameter table does not seem to exist")
  }
  
  # Load parameter name used for the analysis
  name_para <- colnames(param_table)
  
  # Name of parameter used as input parameter in OpenMalaria
  param_names <- c(name_para[3:length(name_para)], 'Degree_resistance_2', "a_1", "b_1", "a_2", "b_2") # change
  
  # Name of parameter used as Output of Openmalaria for the Global sensitivity analysis
  param_names_2 <- c(name_para[3:length(name_para)], "seasonality") # change
  
  # Create two lists of scenario
  
  # liste of scenario with parameter adjusted for the input of OpenMalaria
  Liste_scenario_adjusted <- data.frame(matrix(ncol = length(param_names) + 1, nrow = nrow(param_table)))
  colnames(Liste_scenario_adjusted) <- c(param_names, "scenario_name")
  
  # liste of scenario without adjustement of their values (table used for the sensitivity analysis later)
  Liste_scenario <- data.frame(matrix(ncol = length(param_names_2) + 1, nrow = nrow(param_table)))
  colnames(Liste_scenario) <- c(param_names_2, "scenario_name")
  
  # Initiate progress bar
  pb <- txtProgressBar(min = 0, max = nrow(param_table), initial = 0, width = 100, style = 3)
  
  # Loop through parameter table rows
  for (i in 1:nrow(param_table)) {
    
    # select the ith scenario
    this_scen <- param_table[i,]
    
    # define the seasonality pattern
    this_season <- this_scen$seasonality
    
    
    #---- Creat the table used for the sensitivity analysis (without adjustement)----#
    
    param_values_2 <- c(this_scen[3:length(name_para)])
    
    
    # ---- Adjust the parameter for the input table ---- #
    
    # Adjust efficacy of the vaccine
    this_scen$decay_efficacy <- this_scen$initialEfficacy - (this_scen$decay_efficacy * this_scen$initialEfficacy)
    this_scen$Degree_resistance_2 <- this_scen$decay_efficacy - (this_scen$decay_efficacy * this_scen$Degree_resistance)
    this_scen$Degree_resistance <- this_scen$initialEfficacy - (this_scen$initialEfficacy * this_scen$Degree_resistance)
    
    
    if (this_scen$seasonality == "sesonality2") {
      this_scen$eir <- adjust_EIR(this_scen$eir, this_scen$Access)
    }
    
    # Adjustment needed when we vaccine target children 
    if (pm$opts$Type_analysis == "Vaccine_R_perennial" | pm$opts$Type_analysis == "Vaccine_efficacy_children" | pm$opts$Type_analysis == "Vaccine_R_seasonal" ) {
      
      # Adjust the coverage of the fourth dose
      this_scen$Coverage_reduced <- (1 - this_scen$Coverage_reduced) # X % of children who received initial dose
      
    }
    
    
    if (pm$opts$Type_analysis == "Vaccine_R_adult_AIV" | pm$opts$Type_analysis == "Vaccine_R_adult_AIV_TBV" | pm$opts$Type_analysis == "Vaccine_efficacy_adult") {

      # Adjust the coverage of the fourth dose
      this_scen$Coverage_reduced <- this_scen$Coverage * (1 - this_scen$Coverage_reduced) # X% of population (idepend if alrey received vaccines)
      
    }
    
    
    # Load the furrier coefficient for the seasonality pattern
    seasonality_eir <- pm$settings$seasonality[[this_season]]
    
    # Select all the input parameter that will be used in Openmalaria if the analysis aimed to setimate the selection coeffcient of SMC resistant parasite
    param_values <- c(this_scen[, c(3:length(this_scen))])
    param_values <- c(param_values, seasonality_eir) ##
    
    # Format parameter values to not use scientific notation
    param_format <- format(param_values, scientific = FALSE, trim = TRUE, drop0trailing = TRUE)
    
    # Create sed command replacement pattern for each parameter
    sed_patterns <- paste0("s$@", param_names, "@$", param_format, "$g;")
    
    # save file
    file_name <- paste0(this_scen$scenario_name, "_", this_scen$seed, ".txt")
    file_path <- paste0(pm$pth$sim_sed, file_name)
    write.table(sed_patterns, file = file_path, quote = FALSE, col.names = FALSE, row.names = FALSE)
    
    # Save all info on the scenario (save without and with adjusted parameters)
    Liste_scenario[i,] <- c(param_values_2, this_season, file_name)
    Liste_scenario_adjusted[i,] <- c(param_values[1:(length(param_values))], file_name)
    
    # Update the progress bar
    setTxtProgressBar(pb, i)
    
  } # Close seed loop
  
  # Close progress bar
  close(pb)
  
  # Save the list of scenario with adjustement and without adjustement
  file_name <- paste0(pm$pth$sim_sed, "scenarios_", ".txt")
  write.table(Liste_scenario, file = file_name, row.names = FALSE)
  file_name <- paste0(pm$pth$sim_sed, "scenarios_adjusted_", ".txt")
  write.table(Liste_scenario_adjusted, file = file_name, row.names = FALSE)
  
  # return the number of scenario
  return(nrow(param_table))
  
}

# -------------------------------------------------------------
# Generate scenario xml files from base file using sed patterns.
# -------------------------------------------------------------
generate_xml_files <- function(pm, n_jobs, file_path = NA, sed_path = NA, xml_path = NA) {
  
  # message to the console
  message("  - Generating xml files")
  
  # Create a new log file for the cluster jobs
  log_file <- file.path(pm$pth$log_files, "scicore_log.txt")
  create_bash_log(log_file)
  
  # Add country sub directory to file paths
  sed_country <- paste0(sed_path)
  xml_country <- paste0(xml_path)
  
  # Creat sequence of xml to be run at the same time
  n_seq <- 100
  n_submit <- ceil(n_jobs / n_seq)
  
  # Message to the console
  message("   ~ ", thou_sep(n_submit), " sets of ", thou_sep(n_seq))
  
  # Construct slurm array command for running in parallel
  slurm_array <- paste0("--array=1-", n_submit, "%", 300)
  
  # Concatenate system command
  sys_command <- paste("sbatch", slurm_array, "bash_make_xmls.sh", n_seq, file_path, sed_country, xml_country, log_file)
  
  # Invoke this command
  system(sys_command)
  
  # Wait for all cluster jobs to complete
  wait_for_jobs(pm, log_file, n_jobs)
  
}
